### ISSUE TITLE
TypeError: cannot inherit frozen dataclass from a non-frozen one

### ISSUE THREAD

**Issue by Calvin-L** [wilcoxjay/mypyvy#16]
On my MacOS laptop:

```
$ brew install python@3.8
[...]
$ export PATH="$(brew --prefix)/opt/python@3.8/bin:$PATH"
$ python3 --version
Python 3.8.11
```

```
$ python3 src/mypyvy.py                  
Traceback (most recent call last):
  File "src/mypyvy.py", line 13, in <module>
    import logic
  File "/Users/cloncari/sw/src/mypyvy/src/logic.py", line 18, in <module>
    import typechecker
  File "/Users/cloncari/sw/src/mypyvy/src/typechecker.py", line 1, in <module>
    import syntax
  File "/Users/cloncari/sw/src/mypyvy/src/syntax.py", line 553, in <module>
    class Bool(AbstractExpr):
  File "/usr/local/Cellar/python@3.8/3.8.11/Frameworks/Python.framework/Versions/3.8/lib/python3.8/dataclasses.py", line 1011, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
  File "/usr/local/Cellar/python@3.8/3.8.11/Frameworks/Python.framework/Versions/3.8/lib/python3.8/dataclasses.py", line 896, in _process_class
    raise TypeError('cannot inherit frozen dataclass from a '
TypeError: cannot inherit frozen dataclass from a non-frozen one
```

**Comment by wilcoxjay** [comment]
I reproduced this locally with 3.8.11 but not 3.8.7. I guess something got more strict about dataclasses between then and now? Anyway, fixed by 5b5cb9f3be8a990.

**Comment by wilcoxjay** [comment]
and thanks for the report!!

**Comment by Calvin-L** [comment]
And thanks for the quick fix. :)
