### ISSUE TITLE
UPDR thinks a definition is a transition?

### ISSUE THREAD

**Issue by dranov** [wilcoxjay/mypyvy#20]
Running `mypyvy updr` on the following file fails:

```
sort node
sort quorum

sort node_status
immutable constant st_follower: node_status
immutable constant st_leader: node_status
axiom distinct(st_follower, st_leader)
axiom forall S:node_status. S = st_follower | S = st_leader

mutable function status(node): node_status
mutable relation request_vote_resp(node, node)

init status(N) = st_follower
init !request_vote_resp(N1, N2)

immutable relation member(node, quorum)
axiom [intersection] forall Q1, Q2. exists N. member(N, Q1) & member(N, Q2)

definition is_leader(n: node) = status(n) = st_leader

transition timeout(n: node)
    modifies request_vote_resp
    forall V, C.
        new(request_vote_resp(V, C)) <->
            | request_vote_resp(V, C)
            | V = n & C = n

transition become_leader(n: node, q: quorum)
    modifies status
    & (forall N. member(N, q) -> request_vote_resp(N, n))
    & forall N, S.
        new(status(N) = S) <->
            | N != n & status(N) = S
            | N = n & S = st_leader

# FIXME: using is_leader(n) throws exception when running `mypyvy updr`
# but status(n1) = st_leader works!
safety [single_leader_exception]
    forall n1, n2.
        & is_leader(n1)
        & is_leader(n2)
        -> n1 = n2

# safety [single_leader_works]
#     forall n1, n2.
#         & status(n1) = st_leader
#         & status(n2) = st_leader
#         -> n1 = n2
```

I get the following stack trace:

```
/usr/bin/python3.8 /usr/local/bin/mypyvy updr multipaxos.pyv
checking init:
  implies invariant single_leader_per_term_exception... ok. (0:00:00.000406)
Traceback (most recent call last):
  File "/usr/local/bin/mypyvy", line 730, in <module>
    main()
  File "/usr/local/bin/mypyvy", line 721, in main
    utils.args.main(s)
  File "/usr/local/bin/mypyvy", line 73, in do_updr
    fs.search()
  File "/home/dranov/src/mypyvy/src/updr.py", line 404, in search
    self.establish_safety()
  File "/home/dranov/src/mypyvy/src/updr.py", line 116, in establish_safety
    while bstate := self.find_something_to_block():
  File "/home/dranov/src/mypyvy/src/updr.py", line 143, in find_something_to_block
    eval_res = state.eval(syntax.And(*(self[min_frame_no + 1].summary())))
  File "/home/dranov/src/mypyvy/src/semantics.py", line 384, in eval
    return self.trace.eval(e, starting_index=self.index)
  File "/home/dranov/src/mypyvy/src/semantics.py", line 325, in eval
    return go(full_expr, index=starting_index)
  File "/home/dranov/src/mypyvy/src/semantics.py", line 273, in go
    return p(go(arg, index) for arg in expr.args)
  File "/home/dranov/src/mypyvy/src/semantics.py", line 273, in <genexpr>
    return p(go(arg, index) for arg in expr.args)
  File "/home/dranov/src/mypyvy/src/semantics.py", line 257, in go
    return not go(expr.arg, index)
  File "/home/dranov/src/mypyvy/src/semantics.py", line 297, in go
    return p(one(expr, t) for t in product(*doms))
  File "/home/dranov/src/mypyvy/src/semantics.py", line 297, in <genexpr>
    return p(one(expr, t) for t in product(*doms))
  File "/home/dranov/src/mypyvy/src/semantics.py", line 294, in one
    ans = go(q.body, index)
  File "/home/dranov/src/mypyvy/src/semantics.py", line 273, in go
    return p(go(arg, index) for arg in expr.args)
  File "/home/dranov/src/mypyvy/src/semantics.py", line 273, in <genexpr>
    return p(go(arg, index) for arg in expr.args)
  File "/home/dranov/src/mypyvy/src/semantics.py", line 286, in go
    assert False, f'{d}\n{expr}'
AssertionError: transition is_leader(n:node)
  modifies
  status(n) = st_leader
is_leader(n1)
```

However, commenting out `single_leader_exception` and un-commenting `single_leader_works` terminates without exceptions, even though the two are equivalent.

I do not really understand what's going on here, but it seems to be related to how definitions are unfolded, although the bug seems to arise out of the interaction of multiple things: for instance, commenting out the `& (forall N. member(N, q) -> request_vote_resp(N, n))` line OR the `| V = n & C = n` line (which are not directly related to `status` or `st_leader`), makes `mypyvy updr` not work even on `single_leader_exception`.

**Comment by wilcoxjay** [comment]
I'll have to look more closely, but I think it's fair to say that this bug boils down to "UPDR does not support definitions", which we should fix.

**Comment by wilcoxjay** [comment]
Ah, on further review, this specific stack trace actually boils down to "mypyvy's evaluator for FOL formulas does not support definitions", which we should also fix :)

**Comment by odedp** [comment]
Yes, I think I've ran into this in the past as well. Is there a definition expander that we can use before calling the FOL evaluator, or should we just reimplement the logic of expanding a definition in the FOL evaluator?

**Comment by odedp** [comment]
It would actually be useful to have a printer option to print a mypyvy file without definitions (I did this manually several times to experiment with techniques that didn't support definitions)

**Comment by wilcoxjay** [comment]
Yeah, we've been talking about doing definition expansion earlier in the pipeline for a while. (Currently definitions are only expanded at the very last second, during translation to Z3.) This seems like a good excuse to implement it. Once we have that, it will be easy to print the expanded program as well.

**Comment by odedp** [comment]
I'm starting to get a deja vu feeling. I think we discussed this in the past, and found some examples that make it impossible to expand definitions. Something like:
```
type t
constant a: t
mutable relation p(t)

definition pa() = p(a)

transition foo(a: t)
    modifies p
    & pa
    & !p(a)
    & ...
```

I think we said we would make it a syntax error to shadow a global symbol, and then it is possible to expand definitions, but I don't remember what of it we actually did. Is that right?
