### ISSUE TITLE
Exception thrown when nesting old calls using definitions

### ISSUE THREAD

**Issue by aatxe** [wilcoxjay/mypyvy#4]
When you write something with nested calls to old ordinarily (e.g. `old(sent(N, old(installed(N))))`), you get a nice error message in mypyvy-mode (via flycheck) that tells you that you should not nest uses of old like this.

However, when you do the same thing via a definition, you instead get an exception and a stack trace for it. Here is an example stack trace:

```
Suspicious state from syntax checker mypyvy: Flycheck checker mypyvy returned non-zero exit code 1, but its output contained no errors: Traceback (most recent call last):
  File "/Users/awe/Programming/Python/mypyvy/src/mypyvy.py", line 762, in <module>
    main()
  File "/Users/awe/Programming/Python/mypyvy/src/mypyvy.py", line 737, in main
    prog.resolve()
  File "/Users/awe/Programming/Python/mypyvy/src/syntax.py", line 2407, in resolve
    d.resolve(scope)
  File "/Users/awe/Programming/Python/mypyvy/src/syntax.py", line 1632, in resolve
    syms = symbols_used(scope, self.expr)
  File "/Users/awe/Programming/Python/mypyvy/src/syntax.py", line 299, in symbols_used
    ans |= symbols_used(scope, arg, old)
  File "/Users/awe/Programming/Python/mypyvy/src/syntax.py", line 319, in symbols_used
    return symbols_used(scope, expr.body, old)
  File "/Users/awe/Programming/Python/mypyvy/src/syntax.py", line 295, in symbols_used
    return symbols_used(scope, expr.arg1, old) | symbols_used(scope, expr.arg2,old)
  File "/Users/awe/Programming/Python/mypyvy/src/syntax.py", line 299, in symbols_used
    ans |= symbols_used(scope, arg, old)
  File "/Users/awe/Programming/Python/mypyvy/src/syntax.py", line 319, in symbols_used
    return symbols_used(scope, expr.body, old)
  File "/Users/awe/Programming/Python/mypyvy/src/syntax.py", line 291, in symbols_used
    return symbols_used(scope, expr.arg, old=True)
  File "/Users/awe/Programming/Python/mypyvy/src/syntax.py", line 299, in symbols_used
    ans |= symbols_used(scope, arg, old)
  File "/Users/awe/Programming/Python/mypyvy/src/syntax.py", line 309, in symbols_used
    assert not (old and d.twostate)
AssertionError
```

Unless I'm misunderstanding the purpose of definitions, I believe this is a bug, and it would be desirable to instead report the error to the user much in the same fashion as mypyvy currently does when you just try to nest old calls directly.

Here is a small reproducing example for the exception:
```
sort a

mutable relation foo(a)
mutable relation bar(a)

twostate definition foobar(a: a) = old(foo(a))

transition do_bar(a: a)
  modifies bar
  forall A. bar(A) <-> old(foobar(A))
```

**Comment by wilcoxjay** [comment]
Good catch, thanks!
